name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bookcatalog:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bookcatalog:latest

      - name: Install Helm
        if: github.ref == 'refs/heads/main'
        uses: azure/setup-helm@v4

      - name: Set kubeconfig
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${KUBE_CONFIG}" | base64 -d > $HOME/.kube/config
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy with Helm
        if: github.ref == 'refs/heads/main'
        run: |
          helm upgrade --install bookcatalog ./helm/bookcatalog \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/bookcatalog \
            --set image.tag=latest \
            --wait
