name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/bookcatalog
  IMAGE_TAG: latest
  PYTHON_VERSION: "3.10"

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Install Helm
        if: github.ref == 'refs/heads/main'
        uses: azure/setup-helm@v4

      - name: Set kubeconfig
        if: github.ref == 'refs/heads/main'
        shell: bash
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          set -euo pipefail
          mkdir -p "$HOME/.kube"
          printf "%s" "$KUBE_CONFIG" | base64 -d > "$HOME/.kube/config"


      - name: Debug kubeconfig
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Verificando kubeconfig..."
          ls -l $HOME/.kube/config
          head -n 5 $HOME/.kube/config

      - name: Deploy with Helm
        if: github.ref == 'refs/heads/main'
        run: |
          helm upgrade --install bookcatalog ./helm/bookcatalog \
            --set image.repository=${{ env.IMAGE_NAME }} \
            --set image.tag=${{ env.IMAGE_TAG }} \
            --wait
